### ISSUE TITLE
package `Proto.Cluster.CodeGen` exception

### ISSUE THREAD

**Issue by gsw945** [asynkron/realtimemap#9]
I can't run this project in VS 2019, due to the error of `Proto.Cluster.CodeGen`, exception as below:

error  MSB4062  task "Proto.Cluster.CodeGen.ProtoGenTask" could not be loaded from the assembly C:\Users\xxx\\.nuget\packages\proto.cluster.codegen\0.21.1-alpha.0.15\build\..\tasks\net5.0\Proto.Cluster.CodeGen.dll. Could not load file or assembly 'file:///C:\Users\xxx\\.nuget\packages\proto.cluster.codegen\0.21.1-alpha.0.15\tasks\net5.0\Proto.Cluster.CodeGen.dll' or one of its dependencies.The system cannot find the file specified. Confirm that <UsingTask> declarationis correct， that the assembly and all its dependencies are available，and that the task contains a public class that implements Microsoft.Build.Framework.ITask。  Backend C:\Users\xxx\\.nuget\packages\proto.cluster.codegen\0.21.1-alpha.0.15\build\Proto.Cluster.CodeGen.props    19

![image](https://user-images.githubusercontent.com/6281968/128800061-510c40ff-0f00-470a-8c98-abbce7b894ad.png)

how to solve it?

**Comment by redss** [comment]
This issue is now fixed.
